### ISSUE TITLE
iOS-Swizzling-Guide

### ISSUE THREAD

**Issue by SalavatR** [AppsFlyerSDK/appsflyer-unity-plugin#101]
Fb sdk now recursively login, according to iOS-Swizzling-Guide i add AppsFlyerShouldSwizzle key to info plist, 

can anybody give code example of  AppsFlyer+AppController and AppsFlyerAppController?

fbsdk version 9.2.0
appsflyer >= 6.2.3

**Comment by s-sixteen** [comment]
Having exactly the same problem over here. In my case it was caused by #47

**Comment by af-margot** [comment]
Hi, 

You can now use a macroprocessor to do sizzling in our plugin, without having to touch the file AppsFlyerAppController. Please refer to the doc [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/Troubleshooting.md#-using-macroprocessor). 

In the meantime, I will close this issue because it has been inactive for a while.
Please reopen if you still encounter this issue :)

Thank you!
