### ISSUE TITLE
Can appsflyer be initialized in a non main thread?

### ISSUE THREAD

**Issue by chebedzic** [AppsFlyerSDK/appsflyer-unity-plugin#111]
Im wonderng is it safe to run these 2 methods in a non main thread since the IAppsFlyerConversionData is supposed to be MonoBehaviour:

AppsFlyer.initSDK(....);
AppsFlyer.startSDK();  

My question is are these 2 methods thread-safe, since they take up to 10s on certain devices, and there is nothing about thread safety in documentation/isssues etc..

Thanks.

**Comment by af-margot** [comment]
Hi, 

The issue is quite old, but I would advise using those methods in the main thread. 
Our init method is using `gameObject.name` API, which is a Unity API. If I'm not mistaken UNITY API can only be called from the main thread. 
I’m closing this issue for now because it has been inactive for a while.
Please reopen if you still have some questions about it :) 

Thank you!
