### ISSUE TITLE
Non-organic install test with user declining ATT request

### ISSUE THREAD

**Issue by eatsports** [AppsFlyerSDK/appsflyer-unity-plugin#117]
**VERSIONS**
Unity:   2019.4.24
Appsflyer SDK: 6.3.2
Platform: iOS

**ISSUE**

Hello, i can't seem to find any info regarding the expected result of non-organic install when the user declines the AppTrackingTransparency request.

The test passes just fine if the user agrees to tracking, the install is detected and IDFA is received.
But if the user disagrees and asks not to track, when the non-organic install test just hangs forever, and seemingly no install data is sent.
Is this the expected behavior?

In my app, i do the following:
1) Call AppsFlyer.initSDK
2) Call AppsFlyeriOS.waitForATTUserAuthorizationWithTimeoutInterval
3) Call AppsFlyer.startSDK();
4) Show the ATT popup with the unity method ATTrackingStatusBinding.RequestAuthorizationTracking

Am I doing something wrong?

**Comment by ge-af** [comment]
Hi @eatsports 

In order to record a successful install under Test Page Integration page you will need to accept the ATT popup just like you mentioned you did. This indicates that the SDK integration is correct using Device-Id matching.

Whenever you try to record a non-organic install using a device with **iOS14.5+** we cannot attribute it without IDFA due to the Aggregated Advanced Privacy enabled by default inside your AppsFlyer's dashboard under App Settings.

**Comment by eatsports** [comment]
@ge-af So basically i shouldn't expect that the non-organic test will detect anything if i don't accept the ATT popup?

**Comment by ge-af** [comment]
@eatsports That's right. 
for iOS14.5+ you can't expect a non-organic install through the Test Integration page.
You can try to test it using attribution link like mentioned in this [guide](https://support.appsflyer.com/hc/en-us/articles/360001559405-Test-mobile-SDK-integration-with-the-app#test-with-attribution-links).
It will work using Probabilistic modeling and not with Device-id matching.

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while.
Please reopen if you still encounter this issue :)

Thank you!
