### ISSUE TITLE
 How to adding the App in the AppsFlyer dashboard using the Android Out-of-Store APK option, set the channel. In Unity

### ISSUE THREAD

**Issue by Garfiebobo** [AppsFlyerSDK/appsflyer-unity-plugin#129]
How to adding the App in the AppsFlyer dashboard using the Android Out-of-Store APK option, set the channel. In Unity

**Comment by ge-af** [comment]
Hi @Garfiebobo 

Please follow this guide [here](https://support.appsflyer.com/hc/en-us/articles/207447023-Setting-up-multi-store-Android-attribution-). It should be the same for Unity as well. You can set the channel inside the Android Manifest, if needed.

If any further question has arises, I strongly recommend to submit a support ticket to support@appsflyer.com in order to get optimal support.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while.
Please reopen if you still encounter this issue :)

Thank you!
