### ISSUE TITLE
[IOS] Appsflyer 6.x.x and setIsDebug

### ISSUE THREAD

**Issue by VergilUa** [AppsFlyerSDK/appsflyer-unity-plugin#146]
After updating from 4.x to 6.5.2 native device debug logs seems to be missing for IOS.
Basically setIsDebug(true) does nothing.

Is this intentional, or a bug?

**Comment by af-margot** [comment]
Hi @VergilUa,

Are you still experiencing this issue?

**Comment by VergilUa** [comment]
Hi, I haven't tested on recent versions of AF. 
After those changes we've settled this with our QA, and they no longer need logs to figure out whether AF is working or not.

If native logs on the device are present when flag is set, then it should be fixed. 
So - no idea if its working or not.

**Comment by af-margot** [comment]
Hi @VergilUa,

Thank you for your answer. Yes, the native logs should be present when the flag is true.
I will close this issue for now then and you can re-open it later if needed.

**Comment by dots-alberto-uriarte** [comment]
Hi!

Faced a similar problem recently. Native AppsFlyer logs were showing up in `XCode` but not in `Console.app`. In my case the problem was that I needed to activate "Include Info Messages" and "Include Debug Messages" in the "Action" menu of `Console.app`
<img width="248" alt="Screen Shot 2022-06-20 at 17 22 20" src="https://user-images.githubusercontent.com/100374695/174634804-37dcdc6d-83a5-4a57-8e4d-5b31c05147e2.png">
