### ISSUE TITLE
Unity, iOS Build Error in AFUnityUtils.mm: 'AppsFlyerLib.h' file not found

### ISSUE THREAD

**Issue by ohthepain** [AppsFlyerSDK/appsflyer-unity-plugin#151]
I added 6.5.3 to my Unity project. When building for iOS I get an error in AFUnityUtils.mm: 'AppsFlyerLib.h' file not found. 

AppsFlyerLib.h does not seem to be anywhere in the project.

//
//  AFUnityUtils.mm
//  Unity-iPhone
//
//  Created by Jonathan Wesfield on 24/07/2019.
//

#if __has_include(<AppsFlyerLib/AppsFlyerLib.h>)
#import <AppsFlyerLib/AppsFlyerLib.h>
#else
#import "AppsFlyerLib.h"
#endif

<img width="713" alt="Screenshot 2022-04-06 at 13 32 46" src="https://user-images.githubusercontent.com/2233053/161965568-90354ad9-c64d-48c9-ad1e-d7dd632b42d4.png">

**Comment by ohthepain** [comment]
I see what's going on. I hadn't installed the AppsFlyer library.

**Comment by M-Ansley** [comment]
Hi @ohthepain, we're currently having this same issue on our CI/CD pipeline. If you have the time, could please clarify what you needed to do to address this? 

Also, for some other information, we're using:
- Unity 2020.3.36f1
- appsflyer-unity-plugin.v6.8.4.unitypackage
- EDM4U version 1.2.144
(We haven't previously used cocoapods and haven't needed to make adjustments to an xCode project in the past)

**Comment by M-Ansley** [comment]
Just an update on this in case it helps anyone else: in our case, we went onto the AppsFlyer integration guide and tried installing the required iOS dependencies to the Assets/Plugins/iOS/AppsFlyer folder manually, as mentioned in the "Without EDM4U" section here: https://support.appsflyer.com/hc/en-us/articles/4412863162897

Among the files in the iOS SDK as a static library was the AppsFlyerLib.h file, and once we included this we seem to be able to build for iOS now. 

Not sure whether it's relevant, but we also disabled anything cocoapods-related in iOS Resolver Settings (mainly because we're not sure we need this for our project), but perhaps that'll cause us issues in the long run.
