### ISSUE TITLE
IOS Unity SDK not working. 

### ISSUE THREAD

**Issue by Archi97** [AppsFlyerSDK/appsflyer-unity-plugin#152]
Hi there.
Few days ago I have integrated AppsFlyer  into my unity project. 
After integration tested on Android, everything works great. But on iOS it doesn't. 
I read every article, find some issue - i put package name com.***.*** for ios as app id on AppsFlyer initializing function. Then changed it to app id from app store. Tested with and without 'id' prefix.  But still no result. Did i miss something? 
By the way AppsFlyer is initializing and i'm able to get AppsFlyerId with AppsFlyer.getAppsFlyerId();
Tested with 6.5.2-6.5.4(just new added, not migrating)

Looking forward for reply.

**Comment by ge-af** [comment]
Hi @Archi97 ,
Thank you for reaching out to us.

To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

**Comment by Archi97** [comment]
Ok, but is that to hard to provide help here?? So others can get solution or more information about this kind of issue. 
Ticket submitted already no response. Here you responded  way faster.  My opinion is that i have missed something in Info.plist or somewhere else,  maybe some permissions. 
But i didn't find any information on your docs. 
Thank

**Comment by ge-af** [comment]
Hi @Archi97 

It depends on if you are using our GameObject or not, if the initialization is correct, etc.
Is the problem with attribution flow, deeplinking, some other feature?

The reason as to why iOS "don't work" is not so clear and straight-forward from the description.
To try and resolve this issue, we might need to view SDK debug logs and look deeper into this one. Since those logs may have sensitive information regarding the usage of the SDK inside your app and that it won't be shared with other entities, we recommend to handle this via Support.

I hope it's clear and I believe you will be handled by the Support team ASAP.

**Comment by Lawrence-Abadier** [comment]
I came in here looking for this, I have the same exact problem. Android works correctly and tracks attributions installs which i currently use with Unity CPI ads; but nothing is working correctly on IOS. I'm using the gameobject that comes with the plugin and made sure that the devkey and the iOS App ID are correct. @Archi97  were you able to find a solution for this?

**Comment by Archi97** [comment]
@Lawrence-Abadier Hey there. My issue was the in-app id part, I put the package name for ios (com.***.***) 
After fixing it everything worked.  The only issue that forced me to ask question here is that AppFlyes site track with delay on IOS. 
So for example, if you testing SDK integration for Non-Organic install,   after testing, wait 5-10 minutes, then you will see that it has been counting.
