### ISSUE TITLE
appsflyer-unity-plugin-6.9.4.unitypackage package.json has incorrect version 6.8.3

### ISSUE THREAD

**Issue by Yaski** [AppsFlyerSDK/appsflyer-unity-plugin#209]

**Comment by af-do** [comment]
Hi @Yaski and thank you for reaching out to us!

When importing our 6.9.4 unitypackage, you should get the 6.9.4 version despite the package.json saying 6.8.3, as this file is crucial when you are installing our plugin via UPM and not while using the unitypackage.

In case this issue blocks you from using our plugin, or you get an unexpected wrong version due to this issue - please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com).

When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ and any additional relevant information.
