### ISSUE TITLE
Xcode build error: No visible @interface for 'AppsFlyerLib' declares the selector 'setPluginInfoWith:pluginVersion:additionalParams:'

### ISSUE THREAD

**Issue by Ned11** [AppsFlyerSDK/appsflyer-unity-plugin#226]
Xcode version: 14.3.1
AppsFlyer version: 6.10.30
Unity version: 2021.3.16f1
--

Installed the AF plugin without EDM and manually pasted the iOS SDK files in the project. I noticed the iOS SDK version mentioned [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/releases) refers to iOS SDK `6.10.1`, but when I manually download the iOS SDK from the installation link [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/Installation.md#installation-without-unity-jar-resolver), it retrieves the `6.4.4` version and not the `6.10.1` as intended.

When building, Xcode fails and throws an error in the `AppsFlyeriOSWrapper` file: 
`No visible @interface for 'AppsFlyerLib' declares the selector 'setPluginInfoWith:pluginVersion:additionalParams:'
`

I assume this error is due to `6.4.4` not containing the new parameter. If not, could someone help me download the `6.10.1` iOS SDK version for Unity or help me solve this issue?

--
<img width="1656" alt="Screenshot 2023-07-07 at 22 45 38" src="https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/assets/9102510/363562dc-1265-4d70-ab45-a66509447498">

**Comment by af-do** [comment]
Hi @Ned11,
Thank you for reaching out to us, this is indeed an issue because the older version you use does not include the function, the links to the dependencies on the _Installation_ page should be now up to date starting with our latest release (6.12.10).
If you specifically need version 6.10.1 of the iOS SDK, here is the [link](https://s3.eu-west-1.amazonaws.com/download.appsflyer.com/ios/6.x.x/6.10.x/6.10.1/AF-iOS-SDK-v6.10.1.zip).

If the issue persists after the version switch - please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com) and they will be able to help you further.
When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ production steps
✅ logs
✅ code snippets
✅ and any additional relevant information.
