### ISSUE TITLE
Facing 'AppsFlyerTracker.h' file not found

### ISSUE THREAD

**Issue by guardfromua** [AppsFlyerSDK/appsflyer-unity-plugin#24]
Facing 'AppsFlyerTracker.h' file not found issue on iOS.
using Unity 2018.4.4 and plugin version from 5.2 to 5.4, Xcode 11.5
![image](https://user-images.githubusercontent.com/16779359/87545719-190cc600-c6b1-11ea-884b-aa7a17145c04.png)

**Comment by wesfieldj** [comment]
@guardfromua The issue is likely caused by copepods not pulling the AppsFlyerFramework properly. 


Can you check that in your `.xcworkspace` project that  Pods >AppsFlyerFramework is included?

The plugin uses the `External Dependency Manager for Unity` should include it automatically but maybe there was an issue with the EDM4U.

**Comment by guardfromua** [comment]
@wesfieldj I don't have Podfile in my project.
So how can I view Pods?

**Comment by wesfieldj** [comment]
The EDM4U should generate the Podfile for you. 

See - https://github.com/googlesamples/unity-jar-resolver#ios-resolver-usage

You are using Unity 2018.4.4 which is [supported](https://github.com/googlesamples/unity-jar-resolver#ios-resolver-usage) so the issue must be with the EDM4U and your app.

You can integrate the SDK without EDM4U as seen [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/Installation.md#installation-without-using-unity-jar-resolver), but we would not recommend this unless you have no other choice. 

Can you try to debug why the EDM4U is not generating the Podfile for your app?

**Comment by guardfromua** [comment]
what I did I created those manually and then add AppsFlyerFramework
