### ISSUE TITLE
Appsflyer 6.0.1 behavior changed 

### ISSUE THREAD

**Issue by IgorGalimski** [AppsFlyerSDK/appsflyer-unity-plugin#38]
Hi! I have a question about new version. In the changes I see this method
'AppsFlyeriOS.waitForAdvertisingIdentifierWithTimeoutInterval'

Does the method postpone Appsflyer initialization for timeout?
Thanks!

**Comment by wesfieldj** [comment]
Hi @IgorGalimski,

Yes, this will postpone the launch until either the ATTrackingManager pop-up is closed or the time is up.

Check out the docs [here](https://support.appsflyer.com//hc/en-us/articles/207032066#api-reference-waitforadvertisingidentifier) for more info and an example.

**Comment by IgorGalimski** [comment]
Hi! Thanks for the reply!

**Comment by osamaraza24** [comment]
@wesfieldj  can we skip AppsFlyeriOS.waitForAdvertisingIdentifierWithTimeoutInterval call and call ATTrackingManager Popup explicitly ? then how would SDK behave ?it will use IDFA or not ? because i use Appsflyers for event logging and call native popup in game not before init or STARTSDK , if user allow tracking ,i simply AppsFlyeriOS.setDisableCollectAppleAdSupport(false); or for not set true , checked debug log appsflyer say "IDFA Disable" all time, but in sending event advertise Ids empty but when allow tracking it send advertiseids, is it right flow ?

**Comment by wesfieldj** [comment]
@IgorGalimski @osamaraza24 

Apple has [announced](https://www.forbes.com/sites/johnkoetsier/2020/09/03/idfa-stay-of-execution-apple-delays-new-ios-14-privacy-measures-until-2021/#1a255348569f) that they will delay the need to request IDFA until 2021.
We have made important changes to the SDK to reflect these latest updates by apple.
We will release v6.0.3 of the plugin later this week so please use v6.0.3 going forward. 

In v6.0.3 IDFA will be collected as before even with iOS 14. There is no need for ATTrackingManager pop-up. (for the next few months)

If you use the pop-up and the `waitForATTUserAuthorizationWithTimeoutInterval` then IDFA will only be collected if the user accepts. 

@IgorGalimski all SDK functionality will continue to work without IDFA. Attribution will be based on probabilistic modeling.

@osamaraza24 If you still choose to use ATTrackingManager pop-up and skip the call to  `waitForATTUserAuthorizationWithTimeoutInterval` then the SDK will not receive the IDFA on the first launch, and this will poorly affect attribution. The right flow is to call the wait API before startSDK().

However, once again following apple's lastest [changes](https://www.forbes.com/sites/johnkoetsier/2020/09/03/idfa-stay-of-execution-apple-delays-new-ios-14-privacy-measures-until-2021/#1a255348569f) this flow is not needed until they make ATTrackingManager mandatory to collect IDFA.
