### ISSUE TITLE
IDFA Questions

### ISSUE THREAD

**Issue by MartinGonzalez** [AppsFlyerSDK/appsflyer-unity-plugin#69]
Unity: 2018.4.16 - 2019.4.16
Appsflyer SDK: 6.1.4
Platform: iOS

I have two questions about App Tracking and Appsflyer approach

* Why we need to set waitForATTUserAuthorizationWithTimeoutInterval to 60 or 120?
I've tried waiting after that minute and advertiserId is being collected correctly, so I don't understand why this time.

* Why a timer? I found it really strange to set a time according on "how long the user will take to answer". Why not a callback requesting the idfa or a simple setAdvertisingId method?

**Comment by af-margot** [comment]
Hi @MartinGonzalez , 

Thank you for reaching out!
* You can set it to anytime you want!
* If the user gives his authorization before the time is up, the SDK will start. He won't wait until the end of the timer.
Please see this [doc](https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-V6-X-integration-guide-for-developers#integration-33-configuring-app-tracking-transparency-att-support) for further explanations.

**Comment by MartinGonzalez** [comment]
Thanks for answering.

Can I ask why this approach instead of something more certain? Like a method to set the IDFA or a callback implementation from Appsflyer side?

**Comment by af-margot** [comment]
Hi @MartinGonzalez, 

In order to get the IDFA, you need to implement the ATT framework and request authorization. So what we do, instead of the developer getting the authorization, then getting the IDFA and passing the info back to AppsFlyer, we directly take it once the app gets the authorization(or start the SDK without IDFA, if it was denied). The main goal is to start the SDK as soon as possible.
